### ISSUE TITLE
Character lip flaps do not activate/activate randomly

### ISSUE THREAD

**Issue by defan752** [SpudManTwo/KPT#21]
Lip flaps for characters do not animate when the character voices are playing. They sometimes work randomly.

**Comment by SpudManTwo** [comment]
Expanded description:
There seems to be 4 parts to getting the lip flaps to work correctly.

1.  Set Speaker Name in Script File
2.  Match Speaker Name with a Speaker Name from Eboot.bin
3.  Spoken line must begin with Japanese quotation marks.
4.  ??? (this has yet to be figured out)

If steps 1 - 3 are done, then the game begins to try to use the lip flap movements but crashes immediately afterwards (soft crash).
It seems there's another hidden connection that is causing the game to fail. Solution might be similar or related to #24

**Comment by SpudManTwo** [comment]
Update from playing through the Beta Release Candidate build. It appears as if the lip flaps work perfectly fine in scenes where there is no main character with their back to the screen. It seems like these scenes behave differently in that regard while the scenes with a main character having their back to the screen do not have working lip flaps. Further investigation may be needed but those two cases currently seem to be consistent.

**Comment by SpudManTwo** [comment]
This has now been fixed/resolved in the beta 2 release.
